### PR TITLE
deleting logs and fixing parallel

### PR DESCRIPTION
**Pull request by JakeMacdona1d**

### CODE REVIEW

**Comment by Frank-Duffy** [comment]
@JakeMacdona1d, let me know once your parallel fix is implemented

**Comment by JakeMacdona1d** [comment]
> @JakeMacdona1d, let me know once your parallel fix is implemented

yes

**Review by Frank-Duffy — COMMENTED** [review]
Hi Jake, in the future please ensure that your commits are named in an informative way. What was odd about it? Does this commit address that oddity?

**Comment by JakeMacdona1d** [comment]
> 

There was no issue in the logic of the algorithm. Rather, it was evident that the error was due to the instrument's data buffer failing to update appropriately. Consequently, the query: 'meas'  would return the value of the previous measurement.  For example, if AC voltage was measured, then two-point resistance was measured; querying two-point resistance would return AC voltage. I tried many solutions, one being, querying only once the function was set appropriately. But, even this caused the same error. The solution to the problem, now applied to the program, works by querying 'meas' twice. Meas, is the coupling of the set function command and read query.

**Pull request closed without merging**
